config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :contacts, only: [:new, :create]
  resources :graph, only: [:index, :create]
  root 'main_page#index', as: 'home'

  namespace 'api' do
    namespace 'v1' do
      resources :usersdata
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clicker.rb
class Clicker < ApplicationRecord
end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :name, :validate => true
    attribute :email
    attribute :message, :validate => true
    attribute :filter, :captcha => true

    def headers 
        {
            :subjects => "Contact Form",
            :to => "careers@devbbq.com",
            :from => %("#{name}" <#{email}>)
        }
    end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/api/v1/usersdata_controller.rb
module Api
    module V1
        class UsersdataController < ApplicationController
            def index
                users = User.order('created_at DESC');
                render json: {status: 'SUCCESS', message: 'Loaded articles', data: users}, status: :ok
            end
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    before_action :require_login
    
    def new
        @contact = Contact.new
    end

    def create
        @contact = Contact.new(params[:contact])
        @contact.request = request
        @counter = Clicker.find_or_create_by(dates: Date.today)
        if @contact.deliver
            @counter.clickers += 1
            @counter.save!
        else
            flash.now[:error] = 'Cannot send message.'
            render :new
        end

    end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
end

app/controllers/graph_controller.rb
class GraphController < ApplicationController
    config.parent_controller = "::ApplicationController"

    def index
        unless current_user.nil?
            #Check if it has admin
            unless current_user.admin?
            redirect_to(
                main_app.home_path,
                alert: "You are not permitted to view this page"
            )
            end
        #Need to log in
        else
            redirect_to(
                main_app.sign_in_path,
                alert: "Please sign in"
            )
        end
        @clicker = Clicker.all

        respond_to do |format|
            format.html
        end
    end
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/graph_helper.rb
module GraphHelper
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/views/contacts/create.html.erb
<div class='vertical-center'>
    <div class='container bg-white p-3 rounded'>
        <h1 class='text-center'>Thank you for applying to DevBBQ !</h1>
    </div>
</div>

app/views/contacts/new.html.erb
<style>
.hidden{
    display: none;
}
</style>

<div class='vertical-center'>
    <%= form_for @contact do |f| %>
        <div class="container bg-white p-3 rounded">
            <h1 class ="text-center"> Send Email ! </h1>
            <%= f.label :name, :class => 'labels'%>:
            <br>
            <%= f.text_field :name, required: true, :class => "form-control"%>
            <br>
            <label class='labels'>Email</label>: <%= current_user.email %>
            <%= f.hidden_field :email, :value => current_user.email, :class => "form-control"%>
            <br>
            <%= f.label :message %>:<br>
            <%= f.text_area :message, as: :text, :class => "form-control"%>
            <div class="hidden">
                <%= f.label :filter %><br>
                <%= f.text_field :filter%>
            </div>
            <br>
            <%= f.submit 'Send Mesage', class: 'btn btn-default' %>
        </div>
    <% end %>
</div>

app/views/graph/index.html.erb
<div class ='vertical-center'>
    <div class="container bg-white p-3 rounded">
        <h1>Total Number of Emails per Dates</h1>
        <%= line_chart Clicker.group(:dates).sum(:clickers) %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="height: 100%;">
<head>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>  
  <%= csrf_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <style>
  .users{
    color: white;
    size: 8px;
    padding-top: 30px;
    padding-bottom: 15px;
    position: relative;
    display: block;
    line-height: 20px;
    float: right !important;
  }

  .navbar{
    min-height: 60px !important;
  }

  .nav-link{
    padding-top: 29px !important;
    font-size: 20px !important;
  }
  .beautify{
    font-family: "apercu",sans-serif;
    color: #202121;
    -webkit-font-smoothing: antialiased;
    padding: 20px;
    background-color: #f44336 !important;
    color: white !important;
  }

  .closebtn{
    margin-left: 15px;
    color: white;
    font-weight: bold;
    float: right;
    font-size: 22px;
    line-height: 20px;
    cursor: pointer;
    transition: 0.3s;
  }

  .signout{
    padding-top: 20px; 
  }

  body {
    background: linear-gradient(to top, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.4) 4%, rgba(0, 0, 0, 0.80) 100%), url(/assets/BBQ.jpg) no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    height: 100%;
  }

  .vertical-center {
    min-height: calc(100% - 100px);  /* Fallback for browsers do NOT support vh unit */
    display: flex;
    align-items: center;
  }

  form {
    width: 100%;
  }
  </style>

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to(image_tag('DevBBQ.png', :alt => 'logo'), home_path, :class => 'navbar-brand')%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if signed_in? -%>
            <li class='nav-item'><%= link_to "Career", new_contact_path, :class => 'nav-link' %></li>
              <%if current_user.admin? -%>
                <li class='nav-item'><%= link_to "Admin", rails_admin_path, target: '_self', :class => 'nav-link' %></li>
                <li class='nav-item'><%= link_to "Daily Email", graph_index_path, :class => 'nav-link' %></li>
              <% end %>
      </ul>
        <ul class='navbar-nav ml-auto'>
            <li class='nav-item users' >Signed in as: <%= current_user.email %> &nbsp; </li>
            <li class='nav-item signout'><%= button_to t(".sign_out"), sign_out_path, method: :delete, :class => 'btn btn-general' %></li>
        </ul>
        <% else %>
            <li class='nav-item'><%= link_to t(".sign_in"), sign_in_path, :class => 'nav-link' %></li>
            <li class='nav-item'><%= link_to t(".sign_up"), sign_up_path, :class => 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  
  <div id="flash">
    <% flash.each do |key, value| -%>
      <div class = "beautify" id="flash_<%= key %>">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
        <strong>Danger!</strong>
        <%=h value %>
      </div>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>

app/views/main_page/index.html.erb
<body>
    <div class = "vertical-center">
        <%= image_tag("image.png", :alt => "Welcome!",  :style => 'max-width: 100%;')%>
    </div>
</body>

app/views/users/_form.html.erb
  <div class="text-field form-group">
    <%= form.label :email %>
    <%= form.text_field :email, type: 'email', :class => "form-control" %>
  </div>
  <div class="password-field form-group">
    <%= form.label :password %>
    <%= form.password_field :password, :class => "form-control"  %>
  </div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up vertical-center">
  <div class="container h-100 bg-white p-3 rounded">
  <h1 class="text-center"> Sign up </h1>
    <%= form_for @user do |form| %>
      <%= render partial: '/users/form', object: form %>
      <div class="submit-field">
        <%= form.submit({:class => 'btn btn-default'})%>
      </div>
      <br>
      <div class="other-links">
        <%= link_to "You Already Have an Account ? Sign in !", sign_in_path %>
      </div>
    <% end %>
  </div>
</div>